import 'package:flutter/widgets.dart';

class MazadLocalizations {
  MazadLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('ar'), Locale('en')];

  static const _localizedValues = <String, Map<String, String>>{
    'ar': {
      'home': 'الرئيسية',
      'explore': 'استكشف',
      'wanted': 'طلبات',
      'profile': 'حسابي',
      'settings': 'الإعدادات',
      'wallet': 'المحفظة',
      'chat': 'المحادثات',
      'checkout': 'الدفع',
      'orders': 'الطلبات',
      'favorites': 'المفضلة',
      'reviews': 'التقييمات',
      'support': 'الدعم',
      'merchant': 'لوحة التاجر',
      'theme_system': 'النظام',
      'theme_light': 'فاتح',
      'theme_dark': 'داكن',
      'language': 'اللغة',
      'search_hint': 'ابحث عن مزاد أو طلب',
      'notifications': 'التنبيهات',
      'empty_notifications': 'لا إشعارات بعد',
      'empty_notifications_sub': 'سنعلمك فور وجود تحديثات جديدة',
      'deck_skip': 'تخطي',
      'deck_save': 'حفظ',
      'deck_details': 'التفاصيل',
      'deck_rewind': 'تراجع',
      'rewind_not_available': 'لا يوجد بطاقة للرجوع إليها',
      'settings_theme': 'وضع المظهر',
      'settings_language': 'اللغة والاتجاه',
      'settings_notifications': 'التنبيهات',
      'settings_privacy': 'الخصوصية',
      'settings_notifications_hint': 'تفعيل تنبيهات العروض والطلبات داخلياً',
      'settings_privacy_hint': 'إدارة المستخدمين المحجوبين محلياً',
      'settings_density': 'كثافة الواجهة',
      'settings_seed_color': 'لون الهوية',
      'density_comfortable': 'مريحة',
      'density_compact': 'مضغوطة',
      'pull_to_refresh': 'اسحب للتحديث',
      'end_of_list': 'لقد وصلت إلى النهاية',
      'filters': 'الفلاتر',
      'scope_all': 'الكل',
      'scope_auctions': 'مزادات',
      'scope_wanted': 'طلبات',
      'ending_soon': 'ينتهي قريباً',
      'for_you': 'مقترح لك',
      'new_arrivals': 'وصل حديثاً',
      'most_viewed': 'الأكثر مشاهدة',
      'wanted_highlights': 'طلبات مميزة',
      'no_rewind': 'لا يوجد بطاقة للرجوع إليها',
      'quick_actions': 'إجراءات سريعة',
      'start_now': 'ابدأ الآن',
      'browse_guest': 'تصفح كضيف',
      'auction_details': 'تفاصيل المزاد',
      'place_bid': 'تقديم عرض',
      'create_auction': 'إنشاء مزاد',
      'create_wanted': 'إنشاء طلب',
      'wanted_details': 'تفاصيل الطلب',
      'wallet_balance': 'رصيد المحفظة',
      'chat_conversations': 'محادثات نشطة',
      'checkout_summary': 'ملخص الدفع',
      'orders_timeline': 'تتبع الطلبات',
      'favorites_watchlist': 'قائمة المتابعة',
      'reviews_feedback': 'مراجعات المتجر',
      'support_tickets': 'تذاكر الدعم',
      'merchant_dashboard': 'لوحة التاجر',
      'logout': 'تسجيل الخروج',
      'next': 'التالي',
      'back': 'رجوع',
      'confirm': 'تأكيد',
      'draft_saved': 'تم حفظ المسودة محلياً',
      'request_published': 'تم نشر الطلب محلياً',
      'bid_now': 'زايد الآن',
      'offer_now': 'قدّم عرضاً',
      'register_to_bid': 'سجّل لتزايد',
      'static_pages': 'مركز المحتوى',
      'tap_to_read': 'اضغط للقراءة',
      'content_missing': 'المحتوى غير متوفر',
      'saved_searches': 'عمليات البحث المحفوظة',
      'save_search': 'حفظ البحث',
      'remove': 'إزالة',
      'badges_reputation': 'الشارات والسمعة',
      'storefront': 'متجر البائع',
      'coupons': 'قسائم وعروض',
      'view_all': 'عرض الكل',
    },
    'en': {
      'home': 'Home',
      'explore': 'Explore',
      'wanted': 'Wanted',
      'profile': 'Profile',
      'settings': 'Settings',
      'wallet': 'Wallet',
      'chat': 'Chat',
      'checkout': 'Checkout',
      'orders': 'Orders',
      'favorites': 'Favorites',
      'reviews': 'Reviews',
      'support': 'Support',
      'merchant': 'Merchant',
      'theme_system': 'System',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'language': 'Language',
      'search_hint': 'Search auctions or wanted',
      'notifications': 'Notifications',
      'empty_notifications': 'No notifications yet',
      'empty_notifications_sub': 'We will notify you once updates arrive',
      'deck_skip': 'Skip',
      'deck_save': 'Save',
      'deck_details': 'Details',
      'deck_rewind': 'Rewind',
      'rewind_not_available': 'Nothing to rewind yet',
      'settings_theme': 'Theme mode',
      'settings_language': 'Language & direction',
      'settings_notifications': 'Notifications',
      'settings_privacy': 'Privacy',
      'settings_notifications_hint': 'Enable in-app bidding and matches alerts',
      'settings_privacy_hint': 'Manage locally blocked users',
      'settings_density': 'Interface density',
      'settings_seed_color': 'Seed color',
      'density_comfortable': 'Comfortable',
      'density_compact': 'Compact',
      'pull_to_refresh': 'Pull to refresh',
      'end_of_list': 'You reached the end',
      'filters': 'Filters',
      'scope_all': 'All',
      'scope_auctions': 'Auctions',
      'scope_wanted': 'Wanted',
      'ending_soon': 'Ending soon',
      'for_you': 'For you',
      'new_arrivals': 'New arrivals',
      'most_viewed': 'Most viewed',
      'wanted_highlights': 'Wanted highlights',
      'no_rewind': 'Nothing to rewind yet',
      'quick_actions': 'Quick actions',
      'start_now': 'Start now',
      'browse_guest': 'Browse as guest',
      'auction_details': 'Auction details',
      'place_bid': 'Place bid',
      'create_auction': 'Create auction',
      'create_wanted': 'Create wanted',
      'wanted_details': 'Wanted details',
      'wallet_balance': 'Wallet balance',
      'chat_conversations': 'Active chats',
      'checkout_summary': 'Checkout summary',
      'orders_timeline': 'Orders timeline',
      'favorites_watchlist': 'Watchlist',
      'reviews_feedback': 'Reviews',
      'support_tickets': 'Support tickets',
      'merchant_dashboard': 'Merchant dashboard',
      'logout': 'Logout',
      'next': 'Next',
      'back': 'Back',
      'confirm': 'Confirm',
      'draft_saved': 'Draft saved locally',
      'request_published': 'Request published locally',
      'bid_now': 'Bid now',
      'offer_now': 'Make offer',
      'register_to_bid': 'Register to bid',
      'static_pages': 'Knowledge base',
      'tap_to_read': 'Tap to read',
      'content_missing': 'Content not available',
      'saved_searches': 'Saved searches',
      'save_search': 'Save search',
      'remove': 'Remove',
      'badges_reputation': 'Badges & reputation',
      'storefront': 'Storefront',
      'coupons': 'Coupons',
      'view_all': 'View all',
    },
  };

  String t(String key) {
    final lang = locale.languageCode;
    return _localizedValues[lang]?[key] ?? _localizedValues['en']![key] ?? key;
  }

  static MazadLocalizations of(BuildContext context) {
    return Localizations.of<MazadLocalizations>(context, MazadLocalizations)!;
  }
}

class MazadLocalizationsDelegate extends LocalizationsDelegate<MazadLocalizations> {
  const MazadLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => MazadLocalizations.supportedLocales.contains(Locale(locale.languageCode));

  @override
  Future<MazadLocalizations> load(Locale locale) async => MazadLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<MazadLocalizations> old) => false;
}
