import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const Map<String, Map<String, String>> _localizedValues = <String, Map<String, String>>{
    'en': {
      'home': 'Home',
      'brands': 'Brands',
      'all': 'All',
      'new': 'New',
      'used': 'Used',
      'search': 'Search',
      'compare': 'Compare',
      'add_to_compare': 'Add to Compare',
      'favorites': 'Favorites',
      'catalog': 'Catalog',
      'my_car': 'My Car',
      'settings': 'Settings',
      'ai_explain': 'AI Explain',
      'continue': 'Continue',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'guest': 'Continue as guest',
      'welcome_back': 'Welcome back',
      'login_subtitle': 'Sign in to continue exploring AutoDeck.',
      'login_showcase_title': 'Drive your decision with AutoDeck',
      'login_showcase_subtitle': 'Access immersive previews, curated data, and instant comparisons in one place.',
      'create_account': 'Create account',
      'login_cta': 'Login',
      'forgot_password': 'Forgot password?',
      'email_or_phone': 'Email or phone',
      'password': 'Password',
      'experience_onboarding': 'Preview the experience',
      'auth_feature_3d': 'Immersive 3D spins',
      'auth_feature_compare': 'Smart comparisons',
      'auth_feature_sell': 'List & sell quickly',
      'auth_feature_customize': 'Personalised themes',
      'filter': 'Filter',
      'apply': 'Apply',
      'clear': 'Clear',
      'clear_all': 'Clear all',
      'close': 'Close',
      'saved_searches': 'Saved Searches',
      'save_search': 'Save Search',
      'saved_label': 'saved',
      'recent_views': 'Recently viewed',
      'flip_for_specs': 'Tap again to flip for specs',
      'view_details': 'View details',
      'show_specs': 'Show specs',
      'show_overview': 'Show overview',
      'home_title_primary': 'Buy a Car Anytime, Anywhere',
      'home_subtitle': 'Explore immersive 360° spins and smart comparisons.',
      'search_car': 'Search Car',
      'auto_spin': 'Auto spin',
      'pause_spin': 'Pause spin',
      'frame_scrub': 'Scrub frames',
      'frame_position': 'Frame {index} / {total}',
      'no_cars_found': 'No cars found',
      'adjust_filters': 'Adjust filters',
      'search_saved': 'Search saved',
      'compare_full': 'Compare list is full',
      'condition': 'Condition',
      'favorites_empty': 'No favorites yet',
      'compare_empty': 'Add cars to compare.',
      'dark_mode': 'Dark mode',
      'primary_color': 'Primary color',
      'tap_to_choose': 'Tap to choose',
      'language': 'Language',
      'show_tutorial': 'Show Tutorial',
      'rename_search': 'Rename search',
      'name': 'Name',
      'save': 'Save',
      'select_color': 'Select color',
      'choose_language': 'Choose language',
      'english': 'English',
      'arabic': 'Arabic',
      'create_account_title': 'Create your account',
      'create_account_subtitle': 'Tell us about you to personalise your garage.',
      'have_account_login': 'Have an account? Sign in',
      'full_name': 'Full name',
      'email': 'Email',
      'phone': 'Phone',
      'confirm_password': 'Confirm password',
      'sign_up': 'Sign up',
      'signup_showcase_title': 'Create your AutoDeck profile',
      'signup_showcase_subtitle': 'Save favourites, publish listings, and sync preferences across devices.',
      'auth_safe_signup_hint': 'Your details stay on device during this offline preview.',
      'reset_password_title': 'Reset password',
      'reset_password_subtitle': 'Enter your email or phone to receive a reset link.',
      'send_reset_link': 'Send reset link',
      'reset_link_sent': 'We sent a reset link to your inbox.',
      'sort': 'Sort',
      'newest': 'Newest',
      'price_asc': 'Price ↑',
      'price_desc': 'Price ↓',
      'year_asc': 'Year ↑',
      'year_desc': 'Year ↓',
      'mileage_asc': 'Mileage ↑',
      'mileage_desc': 'Mileage ↓',
      'grid': 'Grid',
      'list': 'List',
      'brand': 'Brand',
      'price': 'Price',
      'year': 'Year',
      'mileage': 'Mileage',
      'fuel': 'Fuel',
      'transmission': 'Transmission',
      'seats': 'Seats',
      'seat': 'seat',
      'city': 'City',
      'car_preview': 'Car preview',
      'hero_viewer': 'Car preview viewer',
      'spec': 'Spec',
      'car': 'Car',
      'specifications': 'Specifications',
      'drivetrain': 'Drivetrain',
      'acceleration': 'Acceleration 0-100',
      'battery_range': 'Battery range',
      'top_speed': 'Top speed',
      'horsepower': 'Horsepower',
      'basics': 'Basics',
      'model': 'Model',
      'description': 'Description',
      'accepting_offers': 'Accepting offers',
      'images_urls': 'Images (URLs)',
      'spinset_urls': '360 Frames (URLs)',
      'one_url_per_line': 'One URL per line',
      'frames': 'Frames',
      'maintenance': 'Maintenance',
      'current_mileage': 'Current mileage',
      'last_oil_change': 'Last oil change (km)',
      'listed_for_sale': 'Listing added to catalog',
      'saved_draft': 'Draft saved locally',
      'offers_watch': 'Offers Watch',
      'offer_watch_hint': 'Add a target price to get notified when a buyer is willing to pay it.',
      'no_offer_watches': 'No offer watches yet',
      'target_price_label': 'Target price',
      'cancel': 'Cancel',
      'add': 'Add',
      'remove': 'Remove',
      'add_offer_watch': 'Add Offer Watch',
      'list_for_sale': 'List for Sale',
      'save_only': 'Save Only',
      'contact_seller': 'Contact Seller (Stub)',
      'contact_placeholder': 'This is a placeholder. Integration will arrive in later phases.',
      'required_field': 'This field is required',
      'enter_valid_email_or_phone': 'Enter a valid email or phone',
      'password_short': 'Use 8+ characters',
      'password_number': 'Add at least one number',
      'enter_valid_name': 'Enter a valid name',
      'invalid_email': 'Invalid email',
      'enter_valid_phone': 'Enter a valid phone',
      'password_mismatch': 'Passwords do not match',
      'hero_viewer_scroll_hint': 'Swipe to spin, pinch or double-tap to explore details.',
      'acceleration_time': '0-100 km/h in {seconds}s',
      'market_pulse': 'Market pulse',
      'stage_five_badge': 'Phase V',
      'avg_price_label': 'Avg. price',
      'avg_mileage_label': 'Avg. mileage',
      'inventory_depth_label': 'Inventory depth',
      'fastest_spin_label': 'Fastest spin',
      'longest_range_label': 'Longest range',
      'inventory_value': '{count} cars live',
      'recommended_for_you': 'Recommended for you',
      'eco_spotlight': 'Eco spotlight',
      'ownership_timeline': 'Ownership timeline',
      'oil_change_now_title': 'Oil change due',
      'oil_change_now_subtitle': 'You are past the recommended interval—book a service soon.',
      'oil_change_next_title': 'Next oil change at {km} km',
      'oil_change_next_subtitle': '{km} km remaining based on your entry.',
      'tire_check_title': 'Rotate & check tires',
      'tire_check_subtitle': 'Plan a tire inspection at {km} km to keep grip optimal.',
      'listing_ready_title': 'Listing readiness',
      'listing_ready_subtitle': '{photos} photos • {frames} 360° frames uploaded.',
      'onboarding_story_1': 'Immersive 360° discovery',
      'onboarding_caption_1': 'Spin every angle with adaptive lighting and neon highlights.',
      'onboarding_story_2': 'Sell smarter in minutes',
      'onboarding_caption_2': 'Publish listings with instant watchers and offers.',
      'onboarding_story_3': 'Make AutoDeck yours',
      'onboarding_caption_3': 'Switch languages, tune the neon accent, and master the tutorial.',
      'next_phase_title': 'Next development phase',
      'next_phase_subtitle': 'See what we are building next',
      'next_phase_heading': 'Roadmap preview',
      'next_phase_intro': 'These initiatives are queued for the connected release once backend services go live.',
      'phase_backend_title': 'Connected listings & analytics',
      'phase_backend_description': 'Integrate the marketplace backend, real bids, and smart analytics dashboards.',
      'phase_notifications_title': 'Live notifications',
      'phase_notifications_description': 'Enable push alerts for offers, saved searches, and maintenance reminders.',
      'phase_ai_title': 'AI insights upgrade',
      'phase_ai_description': 'Generate long-form recommendations, pricing guidance, and image enhancements locally.',
      'phase_finance_title': 'Financing & insurance',
      'phase_finance_description': 'Surface financing calculators, insurance bundles, and dealer partnerships.',
      'phase_social_title': 'Community marketplace signals',
      'phase_social_description': 'Launch social feeds, seller profiles, and chat to build trust.',
      'phase_subscription_title': 'Pro subscriptions',
      'phase_subscription_description': 'Offer dealer workspaces, analytics packs, and white-label themes.',
      'phase_ar_title': 'AR showroom layers',
      'phase_ar_description': 'Drop cars into your driveway using on-device augmented reality previews.',
      'maintenance_tip_oil': 'Time to change engine oil soon.',
      'maintenance_tip_tires': 'Check tire pressure monthly.',
    },
    'ar': {
      'home': 'الرئيسية',
      'brands': 'الماركات',
      'all': 'الكل',
      'new': 'جديدة',
      'used': 'مستعملة',
      'search': 'بحث',
      'compare': 'مقارنة',
      'add_to_compare': 'أضف للمقارنة',
      'favorites': 'المفضلة',
      'catalog': 'الكتالوج',
      'my_car': 'سيارتي',
      'settings': 'الإعدادات',
      'ai_explain': 'تحليل بالذكاء الاصطناعي',
      'continue': 'متابعة',
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'ابدأ الآن',
      'guest': 'الدخول كضيف',
      'welcome_back': 'مرحبًا بعودتك',
      'login_subtitle': 'سجّل الدخول لمتابعة استكشاف أوتودِك.',
      'login_showcase_title': 'اتخذ قرارك مع أوتودِك',
      'login_showcase_subtitle': 'استمتع بمعاينات غامرة وبيانات منسقة ومقارنات فورية في مكان واحد.',
      'create_account': 'إنشاء حساب',
      'login_cta': 'تسجيل الدخول',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'email_or_phone': 'البريد الإلكتروني أو الهاتف',
      'password': 'كلمة المرور',
      'experience_onboarding': 'استكشف التجربة',
      'auth_feature_3d': 'معاينات ثلاثية الأبعاد غامرة',
      'auth_feature_compare': 'مقارنات ذكية',
      'auth_feature_sell': 'اعرض وبِع بسرعة',
      'auth_feature_customize': 'ثيمات مخصصة',
      'filter': 'فلترة',
      'apply': 'تطبيق',
      'clear': 'مسح',
      'clear_all': 'مسح الكل',
      'close': 'إغلاق',
      'saved_searches': 'عمليات بحث محفوظة',
      'save_search': 'حفظ البحث',
      'saved_label': 'محفوظة',
      'recent_views': 'شوفتها مؤخرًا',
      'flip_for_specs': 'اضغط مرة أخرى لقلب البطاقة للمواصفات',
      'view_details': 'عرض التفاصيل',
      'show_specs': 'عرض المواصفات',
      'show_overview': 'عرض الملخص',
      'home_title_primary': 'اشترِ سيارة في أي مكان وزمان',
      'home_subtitle': 'استكشف عرضًا ثلاثي الأبعاد بزاوية 360° ومقارنات ذكية.',
      'search_car': 'ابحث عن سيارة',
      'auto_spin': 'تشغيل الدوران التلقائي',
      'pause_spin': 'إيقاف الدوران',
      'frame_scrub': 'تصفح الإطارات',
      'frame_position': 'الإطار {index} من {total}',
      'no_cars_found': 'لا توجد سيارات',
      'adjust_filters': 'تعديل الفلاتر',
      'search_saved': 'تم حفظ البحث',
      'compare_full': 'قائمة المقارنة ممتلئة',
      'condition': 'الحالة',
      'favorites_empty': 'لا مفضلة بعد',
      'compare_empty': 'أضف سيارات للمقارنة.',
      'dark_mode': 'الوضع الداكن',
      'primary_color': 'اللون الرئيسي',
      'tap_to_choose': 'اضغط للاختيار',
      'language': 'اللغة',
      'show_tutorial': 'عرض الإرشادات',
      'rename_search': 'إعادة تسمية البحث',
      'name': 'الاسم',
      'save': 'حفظ',
      'select_color': 'اختر اللون',
      'choose_language': 'اختر اللغة',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'create_account_title': 'أنشئ حسابك',
      'create_account_subtitle': 'أخبرنا عنك لنخصص معرضك.',
      'have_account_login': 'لديك حساب؟ سجّل الدخول',
      'full_name': 'الاسم الكامل',
      'email': 'البريد الإلكتروني',
      'phone': 'رقم الهاتف',
      'confirm_password': 'تأكيد كلمة المرور',
      'sign_up': 'إنشاء حساب',
      'signup_showcase_title': 'أنشئ ملفك في أوتودِك',
      'signup_showcase_subtitle': 'احفظ المفضلة، وانشر الإعلانات، وزامن تفضيلاتك عبر الأجهزة.',
      'auth_safe_signup_hint': 'تبقى بياناتك على الجهاز خلال هذه النسخة بدون اتصال.',
      'reset_password_title': 'استعادة كلمة المرور',
      'reset_password_subtitle': 'أدخل البريد أو الهاتف لإرسال رابط إعادة التعيين.',
      'send_reset_link': 'أرسل الرابط',
      'reset_link_sent': 'أرسلنا رابط إعادة التعيين إلى بريدك.',
      'sort': 'ترتيب',
      'newest': 'الأحدث',
      'price_asc': 'السعر تصاعدي',
      'price_desc': 'السعر تنازلي',
      'year_asc': 'السنة تصاعدي',
      'year_desc': 'السنة تنازلي',
      'mileage_asc': 'الممشى تصاعدي',
      'mileage_desc': 'الممشى تنازلي',
      'grid': 'شبكي',
      'list': 'قائمة',
      'brand': 'الماركة',
      'price': 'السعر',
      'year': 'السنة',
      'mileage': 'المسافة المقطوعة',
      'fuel': 'نوع الوقود',
      'transmission': 'ناقل الحركة',
      'seats': 'عدد المقاعد',
      'seat': 'مقعد',
      'city': 'المدينة',
      'car_preview': 'معاينة السيارة',
      'hero_viewer': 'عارض السيارة ثلاثي الأبعاد',
      'spec': 'المواصفة',
      'car': 'سيارة',
      'specifications': 'المواصفات',
      'drivetrain': 'نظام الدفع',
      'acceleration': 'التسارع 0-100',
      'battery_range': 'مدى البطارية',
      'top_speed': 'السرعة القصوى',
      'horsepower': 'قوة المحرك',
      'basics': 'الأساسيات',
      'model': 'الموديل',
      'description': 'الوصف',
      'accepting_offers': 'قبول العروض',
      'images_urls': 'روابط الصور',
      'spinset_urls': 'روابط الدوران 360°',
      'one_url_per_line': 'رابط واحد في كل سطر',
      'frames': 'عدد الإطارات',
      'maintenance': 'الصيانة',
      'current_mileage': 'المسافة الحالية (كم)',
      'last_oil_change': 'آخر تغيير زيت (كم)',
      'listed_for_sale': 'تم إضافة السيارة للكتالوج',
      'saved_draft': 'تم حفظ المسودة',
      'offers_watch': 'مراقبة العروض',
      'offer_watch_hint': 'أضف سعراً مستهدفاً لتصلك إشعارات عند وجود من يرغب بالدفع.',
      'no_offer_watches': 'لا توجد مراقبة عروض بعد',
      'target_price_label': 'السعر المستهدف',
      'cancel': 'إلغاء',
      'add': 'إضافة',
      'remove': 'إزالة',
      'add_offer_watch': 'إضافة مراقبة عرض',
      'list_for_sale': 'اعرض للبيع',
      'save_only': 'احفظ فقط',
      'contact_seller': 'تواصل مع البائع (تجريبي)',
      'contact_placeholder': 'هذا مجرد عنصر تجريبي. سيتم التكامل لاحقاً.',
      'required_field': 'هذا الحقل مطلوب',
      'enter_valid_email_or_phone': 'أدخل بريدًا أو رقمًا صالحًا',
      'password_short': 'استخدم 8 أحرف فأكثر',
      'password_number': 'أضف رقمًا واحدًا على الأقل',
      'enter_valid_name': 'أدخل اسمًا صالحًا',
      'invalid_email': 'بريد غير صالح',
      'enter_valid_phone': 'أدخل رقم هاتف صالح',
      'password_mismatch': 'كلمتا المرور غير متطابقتين',
      'hero_viewer_scroll_hint': 'اسحب للدوران، قرّب أو انقر مرتين للتكبير.',
      'acceleration_time': '0-100 كم/س في {seconds} ثانية',
      'market_pulse': 'نبض السوق',
      'stage_five_badge': 'المرحلة ٥',
      'avg_price_label': 'متوسط السعر',
      'avg_mileage_label': 'متوسط الممشى',
      'inventory_depth_label': 'عدد السيارات المتاحة',
      'fastest_spin_label': 'الأسرع تسارعًا',
      'longest_range_label': 'أطول مدى',
      'inventory_value': 'هناك {count} سيارات متاحة',
      'recommended_for_you': 'مقترحات لك',
      'eco_spotlight': 'خيارات اقتصادية',
      'ownership_timeline': 'جدول العناية بالسيارة',
      'oil_change_now_title': 'حان موعد تغيير الزيت',
      'oil_change_now_subtitle': 'تجاوزت الفترة الموصى بها — احجز صيانة قريبًا.',
      'oil_change_next_title': 'تغيير الزيت عند {km} كم',
      'oil_change_next_subtitle': 'متبقي {km} كم بناءً على بياناتك.',
      'tire_check_title': 'فحص وتدوير الإطارات',
      'tire_check_subtitle': 'خطّط لفحص الإطارات عند {km} كم للحفاظ على الثبات.',
      'listing_ready_title': 'جاهزية الإعلان',
      'listing_ready_subtitle': '{photos} صور • {frames} إطارات ٣٦٠° مرفوعة.',
      'onboarding_story_1': 'اكتشاف غامر بزاوية ٣٦٠°',
      'onboarding_caption_1': 'استعرض كل الزوايا بإضاءة متكيفة ولمسات نيون.',
      'onboarding_story_2': 'بع أذكى في دقائق',
      'onboarding_caption_2': 'انشر إعلاناتك مع مراقبين وعروض فورية.',
      'onboarding_story_3': 'اجعل أوتودِك بطابعك',
      'onboarding_caption_3': 'بدّل اللغات وعدّل اللون النيون وتعرّف على الدليل التفاعلي.',
      'next_phase_title': 'المرحلة القادمة للتطوير',
      'next_phase_subtitle': 'اطّلع على ما نعمل عليه لاحقًا',
      'next_phase_heading': 'لمحة عن خارطة الطريق',
      'next_phase_intro': 'هذه المبادرات جاهزة للإطلاق عند تفعيل الخدمات الخلفية.',
      'phase_backend_title': 'ربط القوائم والتحليلات',
      'phase_backend_description': 'دمج السوق الخلفي، العروض الحية، ولوحات التحليلات الذكية.',
      'phase_notifications_title': 'إشعارات فورية',
      'phase_notifications_description': 'تفعيل التنبيهات للعروض، والبحث المحفوظ، وتذكيرات الصيانة.',
      'phase_ai_title': 'ترقية تحليلات الذكاء الاصطناعي',
      'phase_ai_description': 'توليد توصيات مفصلة، وإرشادات تسعير، وتحسين الصور محليًا.',
      'phase_finance_title': 'التمويل والتأمين',
      'phase_finance_description': 'عرض حاسبات التمويل، وباقات التأمين، وشراكات الوكلاء.',
      'phase_social_title': 'إشارات مجتمع السوق',
      'phase_social_description': 'إطلاق موجز اجتماعي، ملفات البائعين، ودردشة لبناء الثقة.',
      'phase_subscription_title': 'اشتراكات احترافية',
      'phase_subscription_description': 'توفير مساحات عمل للوكلاء، وحزم تحليلات، وقوالب مخصصة.',
      'phase_ar_title': 'طبقات عرض الواقع المعزز',
      'phase_ar_description': 'إسقاط السيارات في محيطك باستخدام معاينات الواقع المعزز على الجهاز.',
      'maintenance_tip_oil': 'اقترب موعد تغيير زيت المحرك.',
      'maintenance_tip_tires': 'افحص ضغط الإطارات شهريًا.',
    },
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String t(String key) {
    final values = _localizedValues[locale.languageCode] ?? _localizedValues['en']!;
    return values[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => <String>['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
