import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const Map<String, Map<String, String>> _localizedValues = <String, Map<String, String>>{
    'en': {
      'home': 'Home',
      'brands': 'Brands',
      'all': 'All',
      'new': 'New',
      'used': 'Used',
      'search': 'Search',
      'compare': 'Compare',
      'add_to_compare': 'Add to Compare',
      'favorites': 'Favorites',
      'catalog': 'Catalog',
      'my_car': 'My Car',
      'settings': 'Settings',
      'ai_explain': 'AI Explain',
      'continue': 'Continue',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'guest': 'Continue as guest',
      'filter': 'Filter',
      'apply': 'Apply',
      'clear': 'Clear',
      'clear_all': 'Clear all',
      'close': 'Close',
      'saved_searches': 'Saved Searches',
      'save_search': 'Save Search',
      'saved_label': 'saved',
      'recent_views': 'Recently viewed',
      'flip_for_specs': 'Tap again to flip for specs',
      'view_details': 'View details',
      'show_specs': 'Show specs',
      'show_overview': 'Show overview',
      'no_cars_found': 'No cars found',
      'adjust_filters': 'Adjust filters',
      'search_saved': 'Search saved',
      'compare_full': 'Compare list is full',
      'condition': 'Condition',
      'favorites_empty': 'No favorites yet',
      'compare_empty': 'Add cars to compare.',
      'dark_mode': 'Dark mode',
      'primary_color': 'Primary color',
      'tap_to_choose': 'Tap to choose',
      'language': 'Language',
      'show_tutorial': 'Show Tutorial',
      'rename_search': 'Rename search',
      'name': 'Name',
      'save': 'Save',
      'select_color': 'Select color',
      'choose_language': 'Choose language',
      'english': 'English',
      'arabic': 'Arabic',
      'sort': 'Sort',
      'newest': 'Newest',
      'price_asc': 'Price ↑',
      'price_desc': 'Price ↓',
      'year_asc': 'Year ↑',
      'year_desc': 'Year ↓',
      'mileage_asc': 'Mileage ↑',
      'mileage_desc': 'Mileage ↓',
      'grid': 'Grid',
      'list': 'List',
      'brand': 'Brand',
      'price': 'Price',
      'year': 'Year',
      'mileage': 'Mileage',
      'fuel': 'Fuel',
      'transmission': 'Transmission',
      'seats': 'Seats',
      'seat': 'seat',
      'city': 'City',
      'car_preview': 'Car preview',
      'hero_viewer': 'Car preview viewer',
      'spec': 'Spec',
      'car': 'Car',
      'specifications': 'Specifications',
      'drivetrain': 'Drivetrain',
      'acceleration': 'Acceleration 0-100',
      'battery_range': 'Battery range',
      'top_speed': 'Top speed',
      'horsepower': 'Horsepower',
      'basics': 'Basics',
      'model': 'Model',
      'description': 'Description',
      'accepting_offers': 'Accepting offers',
      'images_urls': 'Images (URLs)',
      'spinset_urls': '360 Frames (URLs)',
      'one_url_per_line': 'One URL per line',
      'frames': 'Frames',
      'maintenance': 'Maintenance',
      'current_mileage': 'Current mileage',
      'last_oil_change': 'Last oil change (km)',
      'listed_for_sale': 'Listing added to catalog',
      'saved_draft': 'Draft saved locally',
      'offers_watch': 'Offers Watch',
      'offer_watch_hint': 'Add a target price to get notified when a buyer is willing to pay it.',
      'no_offer_watches': 'No offer watches yet',
      'target_price_label': 'Target price',
      'cancel': 'Cancel',
      'add': 'Add',
      'remove': 'Remove',
      'add_offer_watch': 'Add Offer Watch',
      'list_for_sale': 'List for Sale',
      'save_only': 'Save Only',
      'contact_seller': 'Contact Seller (Stub)',
      'contact_placeholder': 'This is a placeholder. Integration will arrive in later phases.',
      'required_field': 'This field is required',
      'maintenance_tip_oil': 'Time to change engine oil soon.',
      'maintenance_tip_tires': 'Check tire pressure monthly.',
    },
    'ar': {
      'home': 'الرئيسية',
      'brands': 'الماركات',
      'all': 'الكل',
      'new': 'جديدة',
      'used': 'مستعملة',
      'search': 'بحث',
      'compare': 'مقارنة',
      'add_to_compare': 'أضف للمقارنة',
      'favorites': 'المفضلة',
      'catalog': 'الكتالوج',
      'my_car': 'سيارتي',
      'settings': 'الإعدادات',
      'ai_explain': 'تحليل بالذكاء الاصطناعي',
      'continue': 'متابعة',
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'ابدأ الآن',
      'guest': 'الدخول كضيف',
      'filter': 'فلترة',
      'apply': 'تطبيق',
      'clear': 'مسح',
      'clear_all': 'مسح الكل',
      'close': 'إغلاق',
      'saved_searches': 'عمليات بحث محفوظة',
      'save_search': 'حفظ البحث',
      'saved_label': 'محفوظة',
      'recent_views': 'شوفتها مؤخرًا',
      'flip_for_specs': 'اضغط مرة أخرى لقلب البطاقة للمواصفات',
      'view_details': 'عرض التفاصيل',
      'show_specs': 'عرض المواصفات',
      'show_overview': 'عرض الملخص',
      'no_cars_found': 'لا توجد سيارات',
      'adjust_filters': 'تعديل الفلاتر',
      'search_saved': 'تم حفظ البحث',
      'compare_full': 'قائمة المقارنة ممتلئة',
      'condition': 'الحالة',
      'favorites_empty': 'لا مفضلة بعد',
      'compare_empty': 'أضف سيارات للمقارنة.',
      'dark_mode': 'الوضع الداكن',
      'primary_color': 'اللون الرئيسي',
      'tap_to_choose': 'اضغط للاختيار',
      'language': 'اللغة',
      'show_tutorial': 'عرض الإرشادات',
      'rename_search': 'إعادة تسمية البحث',
      'name': 'الاسم',
      'save': 'حفظ',
      'select_color': 'اختر اللون',
      'choose_language': 'اختر اللغة',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'sort': 'ترتيب',
      'newest': 'الأحدث',
      'price_asc': 'السعر تصاعدي',
      'price_desc': 'السعر تنازلي',
      'year_asc': 'السنة تصاعدي',
      'year_desc': 'السنة تنازلي',
      'mileage_asc': 'الممشى تصاعدي',
      'mileage_desc': 'الممشى تنازلي',
      'grid': 'شبكي',
      'list': 'قائمة',
      'brand': 'الماركة',
      'price': 'السعر',
      'year': 'السنة',
      'mileage': 'المسافة المقطوعة',
      'fuel': 'نوع الوقود',
      'transmission': 'ناقل الحركة',
      'seats': 'عدد المقاعد',
      'seat': 'مقعد',
      'city': 'المدينة',
      'car_preview': 'معاينة السيارة',
      'hero_viewer': 'عارض السيارة ثلاثي الأبعاد',
      'spec': 'المواصفة',
      'car': 'سيارة',
      'specifications': 'المواصفات',
      'drivetrain': 'نظام الدفع',
      'acceleration': 'التسارع 0-100',
      'battery_range': 'مدى البطارية',
      'top_speed': 'السرعة القصوى',
      'horsepower': 'قوة المحرك',
      'basics': 'الأساسيات',
      'model': 'الموديل',
      'description': 'الوصف',
      'accepting_offers': 'قبول العروض',
      'images_urls': 'روابط الصور',
      'spinset_urls': 'روابط الدوران 360°',
      'one_url_per_line': 'رابط واحد في كل سطر',
      'frames': 'عدد الإطارات',
      'maintenance': 'الصيانة',
      'current_mileage': 'المسافة الحالية (كم)',
      'last_oil_change': 'آخر تغيير زيت (كم)',
      'listed_for_sale': 'تم إضافة السيارة للكتالوج',
      'saved_draft': 'تم حفظ المسودة',
      'offers_watch': 'مراقبة العروض',
      'offer_watch_hint': 'أضف سعراً مستهدفاً لتصلك إشعارات عند وجود من يرغب بالدفع.',
      'no_offer_watches': 'لا توجد مراقبة عروض بعد',
      'target_price_label': 'السعر المستهدف',
      'cancel': 'إلغاء',
      'add': 'إضافة',
      'remove': 'إزالة',
      'add_offer_watch': 'إضافة مراقبة عرض',
      'list_for_sale': 'اعرض للبيع',
      'save_only': 'احفظ فقط',
      'contact_seller': 'تواصل مع البائع (تجريبي)',
      'contact_placeholder': 'هذا مجرد عنصر تجريبي. سيتم التكامل لاحقاً.',
      'required_field': 'هذا الحقل مطلوب',
      'maintenance_tip_oil': 'اقترب موعد تغيير زيت المحرك.',
      'maintenance_tip_tires': 'افحص ضغط الإطارات شهريًا.',
    },
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String t(String key) {
    final values = _localizedValues[locale.languageCode] ?? _localizedValues['en']!;
    return values[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => <String>['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
